//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryEngineConverterTool.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("X:\\path\\to\\cgf-converter.exe")]
        public string CgfConverterExecutablePath {
            get {
                return ((string)(this["CgfConverterExecutablePath"]));
            }
            set {
                this["CgfConverterExecutablePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bExportCollada {
            get {
                return ((bool)(this["bExportCollada"]));
            }
            set {
                this["bExportCollada"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bExportBlend {
            get {
                return ((bool)(this["bExportBlend"]));
            }
            set {
                this["bExportBlend"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bExportFbx {
            get {
                return ((bool)(this["bExportFbx"]));
            }
            set {
                this["bExportFbx"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bFlagSmoothFaces {
            get {
                return ((bool)(this["bFlagSmoothFaces"]));
            }
            set {
                this["bFlagSmoothFaces"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bFlagsGroupMeshes {
            get {
                return ((bool)(this["bFlagsGroupMeshes"]));
            }
            set {
                this["bFlagsGroupMeshes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bFlagsNoConflict {
            get {
                return ((bool)(this["bFlagsNoConflict"]));
            }
            set {
                this["bFlagsNoConflict"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bFlagsAllowConflict {
            get {
                return ((bool)(this["bFlagsAllowConflict"]));
            }
            set {
                this["bFlagsAllowConflict"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("X:\\path\\to\\objects\\dir")]
        public string ObjectsPath {
            get {
                return ((string)(this["ObjectsPath"]));
            }
            set {
                this["ObjectsPath"] = value;
            }
        }
    }
}
